//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CC001：登録してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC001 {
            get {
                return ResourceManager.GetString("CC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC002：編集中のデータは破棄されますが、処理を続けてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC002 {
            get {
                return ResourceManager.GetString("CC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC003：選択しているデータを削除してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC003 {
            get {
                return ResourceManager.GetString("CC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC004：編集中の定義データを削除してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC004 {
            get {
                return ResourceManager.GetString("CC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC005：当該定義を使った作業中のデータが存在するため、保存・登録ができない可能性があります。保存・登録するためには、この定義が使用されている作業中のデータの処理を全て完了してください。編集画面を表示してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC005 {
            get {
                return ResourceManager.GetString("CC005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC006：保存してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC006 {
            get {
                return ResourceManager.GetString("CC006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC021：編集中のデータ（ユーザ定義画面、書式設定画面での編集中のデータも含む）は破棄されますが、キャンセルしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC021 {
            get {
                return ResourceManager.GetString("CC021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC024：表示中の認識結果データを削除してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC024 {
            get {
                return ResourceManager.GetString("CC024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC025：当該定義を使った保存済みのデータが存在しています。登録する際には、該当する保存済みのデータは削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC025 {
            get {
                return ResourceManager.GetString("CC025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC026：当該定義を使った保存済みのデータが存在しています。保存する際には、該当する保存済みのデータは削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC026 {
            get {
                return ResourceManager.GetString("CC026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC027：この操作を行うと、この項目に紐づくアクション設定が削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC027 {
            get {
                return ResourceManager.GetString("CC027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC028：当該定義を使った保存済みのデータが存在しています。登録または保存する際には、該当する保存済みのデータは削除する必要があります。編集画面を表示してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC028 {
            get {
                return ResourceManager.GetString("CC028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC029：当該定義を使った保存済みのデータが存在しています。登録する際には、該当する保存済みのデータは削除する必要があります。編集画面を表示してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC029 {
            get {
                return ResourceManager.GetString("CC029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC031：この編集を行う場合、設定済の出力項目設計・ユーザ定義・書式設定情報は削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC031 {
            get {
                return ResourceManager.GetString("CC031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC032：削除しようとしているテンプレートが「一覧表示項目」プルダウンにて選択されています。「一覧表示項目」プルダウンも削除してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CC032 {
            get {
                return ResourceManager.GetString("CC032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CO018：エラー項目がありますが、保存してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CO018 {
            get {
                return ResourceManager.GetString("CO018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP001：サービスを起動しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP001 {
            get {
                return ResourceManager.GetString("CP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP002：サービスを停止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP002 {
            get {
                return ResourceManager.GetString("CP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP003：サービスが起動されていませんが、終了してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP003 {
            get {
                return ResourceManager.GetString("CP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP004：帳票認識が出来なくなる可能性があります。選択しているデータを削除しますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP004 {
            get {
                return ResourceManager.GetString("CP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP005：認識結果修正画面生成されません。入力データを一時的に保存してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP005 {
            get {
                return ResourceManager.GetString("CP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP006：項目情報が設定されていないフレームがありますが、よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP006 {
            get {
                return ResourceManager.GetString("CP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP008：帳票選択が変更されたため、出力設定の「処理設定」が”強制的に認識する”から”処理しない”に変更されます。変更したくない場合は、［キャンセル］ボタンクリック後、認識ページ番号が設定されていない帳票定義を選択し直してください。変更してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP008 {
            get {
                return ResourceManager.GetString("CP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP009：パスワードの変更に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP009 {
            get {
                return ResourceManager.GetString("CP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP010：確認対象の認識結果は存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP010 {
            get {
                return ResourceManager.GetString("CP010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP011：帳票認識に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP011 {
            get {
                return ResourceManager.GetString("CP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP012：一時保存していない編集中のデータは破棄されますが、ログアウトしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP012 {
            get {
                return ResourceManager.GetString("CP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP013：認識結果の一時保存に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP013 {
            get {
                return ResourceManager.GetString("CP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP014：一時保存していない編集中のデータは破棄されますが、認識結果修正アプリケーションを終了してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP014 {
            get {
                return ResourceManager.GetString("CP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP015：選択されたテンプレートを削除します。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP015 {
            get {
                return ResourceManager.GetString("CP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP016：選択テンプレートが解除されたため、出力項目設計・ユーザ定義は削除されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP016 {
            get {
                return ResourceManager.GetString("CP016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP017：選択テンプレートに削除されたテンプレートが選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP017 {
            get {
                return ResourceManager.GetString("CP017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP018：切り替え前に設定されていた出力項目設計・ユーザ定義・ユーザ定義の書式設定は削除されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP018 {
            get {
                return ResourceManager.GetString("CP018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP019：確認中の認識結果を修正しようとしていますが、よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP019 {
            get {
                return ResourceManager.GetString("CP019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP021：この帳票で認識を行います。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP021 {
            get {
                return ResourceManager.GetString("CP021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP022：認識処理を開始しました。処理完了後、再度結果修正画面で確認できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP022 {
            get {
                return ResourceManager.GetString("CP022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP023：現在表示中の認識結果データをどうしますか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP023 {
            get {
                return ResourceManager.GetString("CP023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP025：表示条件の保存が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP025 {
            get {
                return ResourceManager.GetString("CP025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP026：ログアウトしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP026 {
            get {
                return ResourceManager.GetString("CP026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP027：認識結果アプリケーションを終了してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP027 {
            get {
                return ResourceManager.GetString("CP027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP028：選択されたグループ項目にてグループ化を解除します。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP028 {
            get {
                return ResourceManager.GetString("CP028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP030：すべてのテンプレート項目をチェックリスト項目として作成します。すでに作成されているチェックリスト項目はすべて削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP030 {
            get {
                return ResourceManager.GetString("CP030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP031：チェックリスト項目として設定済のテンプレート項目が修正または削除されました。登録する場合、該当するチェックリスト項目と、そのチェックリスト項目に紐付く以下設定もすべて削除されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP031 {
            get {
                return ResourceManager.GetString("CP031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP032：画像辞書ファイルが存在しないため、編集時に「特徴点抽出」を実施する必要があります。編集画面を表示してよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP032 {
            get {
                return ResourceManager.GetString("CP032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP033：タブ順に不正があるため、自動で振りなおします。よろしいですか。
        ///※現在あるタブ順の最大値+10ずつ振りなおされます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP033 {
            get {
                return ResourceManager.GetString("CP033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP037：帳票定義にて設定済のチェックリスト項目が修正または削除されました。登録する場合、そのチェックリスト項目に紐付く以下設定もすべて削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP037 {
            get {
                return ResourceManager.GetString("CP037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP038：帳票定義にて設定済のチェックリスト項目が修正または削除されました。保存する場合、そのチェックリスト項目に紐付く以下設定もすべて削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP038 {
            get {
                return ResourceManager.GetString("CP038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP039：選択した帳票定義を有効状態で登録してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP039 {
            get {
                return ResourceManager.GetString("CP039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP040：選択した帳票定義を無効状態で登録してもよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP040 {
            get {
                return ResourceManager.GetString("CP040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP041：選択した範囲内にあるすでに作成されているフレームはすべて削除されます。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP041 {
            get {
                return ResourceManager.GetString("CP041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CP042：現在表示中のタブの項目一覧の内容をすべて出力項目に追加します。よろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CP042 {
            get {
                return ResourceManager.GetString("CP042", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DELETEDDATA {
            get {
                return ResourceManager.GetString("DELETEDDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC001：必須項目の入力・選択をしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC001 {
            get {
                return ResourceManager.GetString("EC001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC002：正しい形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC002 {
            get {
                return ResourceManager.GetString("EC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC003：１つ以上の行を入力・選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC003 {
            get {
                return ResourceManager.GetString("EC003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC004：既にデータが削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC004 {
            get {
                return ResourceManager.GetString("EC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC005：当該定義を使った作業中のデータが存在するため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC005 {
            get {
                return ResourceManager.GetString("EC005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC006：ログイン中のユーザ定義が削除されたため、登録処理を継続できません。編集中のデータを破棄してログアウトします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC006 {
            get {
                return ResourceManager.GetString("EC006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC010：ログイン中のユーザ定義が削除されたため、処理を継続できません。ログアウトします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC010 {
            get {
                return ResourceManager.GetString("EC010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC011：データベースのアクセスに失敗したため、処理を継続できません。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC011 {
            get {
                return ResourceManager.GetString("EC011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC012：帳票画像の読込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC012 {
            get {
                return ResourceManager.GetString("EC012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC013：システム辞書ファイルが存在しないため、アプリケーションの再インストールが必要です。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC013 {
            get {
                return ResourceManager.GetString("EC013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC014：当該定義を使った作業中のデータが存在するため、保存・登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC014 {
            get {
                return ResourceManager.GetString("EC014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC015：当該定義を使った作業中のデータが存在するため、無効化できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC015 {
            get {
                return ResourceManager.GetString("EC015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC016：{0}が最大件数を超えています。管理者に連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC016 {
            get {
                return ResourceManager.GetString("EC016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC017：予期せぬエラーが発生しました。管理者に連絡してください。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC017 {
            get {
                return ResourceManager.GetString("EC017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC018：セッション情報が不正です。ログアウトしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC018 {
            get {
                return ResourceManager.GetString("EC018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC019：システムエラーが発生しました。&lt;br/&gt;大変申し訳ありませんが、システム管理者までご連絡ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC019 {
            get {
                return ResourceManager.GetString("EC019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EC020：アプリケーションエラーが発生しました。{0}{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EC020 {
            get {
                return ResourceManager.GetString("EC020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP001：既にアプリケーションが起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP001 {
            get {
                return ResourceManager.GetString("EP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP002：強制認識する場合、１件のテンプレート設計に紐づく単一帳票の帳票定義データしか選択できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP002 {
            get {
                return ResourceManager.GetString("EP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP003：項目種別に対する必須項目の入力・選択をしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP003 {
            get {
                return ResourceManager.GetString("EP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP004：範囲の指定を正しく入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP004 {
            get {
                return ResourceManager.GetString("EP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP005：変換元文字・変換先文字を正しく入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP005 {
            get {
                return ResourceManager.GetString("EP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP006：変換元文字を重複しないように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP006 {
            get {
                return ResourceManager.GetString("EP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP008：構文を正しく入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP008 {
            get {
                return ResourceManager.GetString("EP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP009：当該データは帳票定義で登録されているため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP009 {
            get {
                return ResourceManager.GetString("EP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP011：「帳票認識ログ：出力設定」グループボックスのフォルダパスにアクセスできないため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP011 {
            get {
                return ResourceManager.GetString("EP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP012：入力されているフォルダは他の監視フォルダデータで利用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP012 {
            get {
                return ResourceManager.GetString("EP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP013：「操作ログ：出力設定」グループボックスのフォルダパスにアクセスできないため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP013 {
            get {
                return ResourceManager.GetString("EP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP014：「選択済テンプレート」内のテンプレートが重複しないように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP014 {
            get {
                return ResourceManager.GetString("EP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP015：「選択済テンプレート」内の「頁」列の値が重複しないように、すべての行に入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP015 {
            get {
                return ResourceManager.GetString("EP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP016：帳票識別に使用可能な項目は３つまでです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP016 {
            get {
                return ResourceManager.GetString("EP016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP017：選択している帳票定義は、監視フォルダで登録されているため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP017 {
            get {
                return ResourceManager.GetString("EP017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP020：入力画像出力フォルダパスにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP020 {
            get {
                return ResourceManager.GetString("EP020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP025：出力先フォルダパスにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP025 {
            get {
                return ResourceManager.GetString("EP025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP027：複数枚の帳票認識を定義している帳票定義データは複数件選択出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP027 {
            get {
                return ResourceManager.GetString("EP027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP028：チェックリスト設計データが存在しないため削除出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP028 {
            get {
                return ResourceManager.GetString("EP028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP029：&quot;SELECT&quot;で始まる半角英字しか入力出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP029 {
            get {
                return ResourceManager.GetString("EP029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP030：入力されているログインIDは既に使用されているため登録出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP030 {
            get {
                return ResourceManager.GetString("EP030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP032：ユーザIDは必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP032 {
            get {
                return ResourceManager.GetString("EP032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP033：パスワードは必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP033 {
            get {
                return ResourceManager.GetString("EP033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP034：認証に失敗しました。ユーザIDが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP034 {
            get {
                return ResourceManager.GetString("EP034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP035：認証に失敗しました。パスワードが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP035 {
            get {
                return ResourceManager.GetString("EP035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP036：パスワードが90日以上変更されていません。パスワードを変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP036 {
            get {
                return ResourceManager.GetString("EP036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP037：新しいパスワードは必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP037 {
            get {
                return ResourceManager.GetString("EP037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP038：現在のパスワードと同じものを設定することは出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP038 {
            get {
                return ResourceManager.GetString("EP038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP039：新しいパスワードと確認用のパスワードが一致していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP039 {
            get {
                return ResourceManager.GetString("EP039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP041：存在しないデータソース名が設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP041 {
            get {
                return ResourceManager.GetString("EP041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP042：以下のグループIDのアクションを再設定してください。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP042 {
            get {
                return ResourceManager.GetString("EP042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP045：画像辞書ファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP045 {
            get {
                return ResourceManager.GetString("EP045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP046：チェックリスト設計が更新されたため、帳票定義設計の再登録が必要です。［編集］ボタンより登録処理を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP046 {
            get {
                return ResourceManager.GetString("EP046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP047：帳票イメージ画像ファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP047 {
            get {
                return ResourceManager.GetString("EP047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP048：出力項目として設定したシステム項目または表示グループ項目にて、書式の設定が一致していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP048 {
            get {
                return ResourceManager.GetString("EP048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP050：マスタ参照で設定したテーブルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP050 {
            get {
                return ResourceManager.GetString("EP050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP051：マスタ参照で設定したテーブル項目が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP051 {
            get {
                return ResourceManager.GetString("EP051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP052：{0}の帳票定義にてエラーがあるため、認識結果修正にて使用できません。ログインしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP052 {
            get {
                return ResourceManager.GetString("EP052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP053：当該データは帳票定義またはチェックリストで登録されているため、削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP053 {
            get {
                return ResourceManager.GetString("EP053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP054：テンプレートの作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP054 {
            get {
                return ResourceManager.GetString("EP054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP055：帳票定義にて、削除されたテンプレートが設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP055 {
            get {
                return ResourceManager.GetString("EP055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP056：一覧表示項目にて、削除されたテンプレートまたは表示グループ項目が設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP056 {
            get {
                return ResourceManager.GetString("EP056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP057：帳票定義（テンプレート選択）にエラーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP057 {
            get {
                return ResourceManager.GetString("EP057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP058：帳票定義（出力設定）にエラーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP058 {
            get {
                return ResourceManager.GetString("EP058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP060：出力項目にて、削除されたテンプレートまたは表示グループ項目（一部のテンプレート項目が削除された場合も含む）が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP060 {
            get {
                return ResourceManager.GetString("EP060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP061：出力項目として設定されたユーザ定義項目にて、削除されたテンプレートまたは表示グループ項目（一部のテンプレート項目が削除された場合も含む）が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP061 {
            get {
                return ResourceManager.GetString("EP061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP062：削除されている帳票定義が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP062 {
            get {
                return ResourceManager.GetString("EP062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP063：表示条件に誤りがあります。赤枠の箇所を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP063 {
            get {
                return ResourceManager.GetString("EP063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP065：保存済みの認識結果を修正することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP065 {
            get {
                return ResourceManager.GetString("EP065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP066：対象の認識結果を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP066 {
            get {
                return ResourceManager.GetString("EP066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP067：確認待ち以外の認識結果を削除することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP067 {
            get {
                return ResourceManager.GetString("EP067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP068：エラー項目が存在するため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP068 {
            get {
                return ResourceManager.GetString("EP068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP071：出力フォーマット設定にエラーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP071 {
            get {
                return ResourceManager.GetString("EP071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP072：出力項目設定にエラーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP072 {
            get {
                return ResourceManager.GetString("EP072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP073：「選択済テンプレート」グリッドビューにてテンプレートが複数選択されているため、単数枚帳票に切り替えられません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP073 {
            get {
                return ResourceManager.GetString("EP073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP075：１つ以上の帳票定義を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP075 {
            get {
                return ResourceManager.GetString("EP075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP076：全ての帳票定義にてエラーがあるため、認識結果修正にて使用できません。ログインしてよろしいですか。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP076 {
            get {
                return ResourceManager.GetString("EP076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP077：マスタ参照、または、論理演算が設定された項目が変更されているため、画面の更新が必要です。「再検査」ボタンクリック後に再度実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP077 {
            get {
                return ResourceManager.GetString("EP077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP078：保存済みの認識結果を削除することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP078 {
            get {
                return ResourceManager.GetString("EP078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP079：帳票を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP079 {
            get {
                return ResourceManager.GetString("EP079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP081：監視フォルダパスにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP081 {
            get {
                return ResourceManager.GetString("EP081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP082：帳票出力設定のフォルダパスにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP082 {
            get {
                return ResourceManager.GetString("EP082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP083：認識結果データが削除されたか、作業ステータスが「保存済み」であるため、登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP083 {
            get {
                return ResourceManager.GetString("EP083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP084：数値形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP084 {
            get {
                return ResourceManager.GetString("EP084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP085：日付形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP085 {
            get {
                return ResourceManager.GetString("EP085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP086：時刻形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP086 {
            get {
                return ResourceManager.GetString("EP086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP087：マークの数が指定された範囲外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP087 {
            get {
                return ResourceManager.GetString("EP087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP088：入力桁数が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP088 {
            get {
                return ResourceManager.GetString("EP088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP089：チェックサム結果が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP089 {
            get {
                return ResourceManager.GetString("EP089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP090：マスタ参照結果が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP090 {
            get {
                return ResourceManager.GetString("EP090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP091：論理演算結果が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP091 {
            get {
                return ResourceManager.GetString("EP091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP092：IDまたはパスワードが間違っているか、タイムアウトが発生したため、DBに接続できません。システム管理者にお問い合わせください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP092 {
            get {
                return ResourceManager.GetString("EP092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP093：知識辞書ファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP093 {
            get {
                return ResourceManager.GetString("EP093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP094：帳票定義にて、1つ以上の出力項目を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP094 {
            get {
                return ResourceManager.GetString("EP094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP095：帳票定義で設定している各テンプレートにて、1つ以上の出力項目を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP095 {
            get {
                return ResourceManager.GetString("EP095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP096：出力項目にて、削除されたユーザ定義項目が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP096 {
            get {
                return ResourceManager.GetString("EP096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP097：テンプレート設計が更新されたため、チェックリスト設計と帳票定義設計の再登録が必要です。以下のテンプレート設計に紐付くチェックリスト設計の登録処理を実施後、再度帳票定義を開始してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP097 {
            get {
                return ResourceManager.GetString("EP097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP098：項目数が最大数に達したため、これ以上項目を追加することはできません。　　←。を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP098 {
            get {
                return ResourceManager.GetString("EP098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP099：ファイル出力に失敗したため、作業ステータスを「一時保存」として登録しました。管理者に連絡してください。シーケンス番号は{0}です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP099 {
            get {
                return ResourceManager.GetString("EP099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP101：対象の行を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP101 {
            get {
                return ResourceManager.GetString("EP101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP102：対象のテンプレートが削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP102 {
            get {
                return ResourceManager.GetString("EP102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP103：削除されたチェックリストグループ項目（一部のテンプレート項目が削除された場合も含む）が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP103 {
            get {
                return ResourceManager.GetString("EP103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP104：削除されたテンプレートまたは表示グループ項目（一部のテンプレート項目が削除された場合も含む）が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP104 {
            get {
                return ResourceManager.GetString("EP104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP105：入力された数値の範囲が正しくありません({0}-{1})。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP105 {
            get {
                return ResourceManager.GetString("EP105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP107：文字種別が設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP107 {
            get {
                return ResourceManager.GetString("EP107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP108：認識種別：{0}は指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP108 {
            get {
                return ResourceManager.GetString("EP108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP109：認識フォームには[9XxKJ*]のいずれかを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP109 {
            get {
                return ResourceManager.GetString("EP109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP110：認識フォームに[{0}]は指定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP110 {
            get {
                return ResourceManager.GetString("EP110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP112：知識辞書が読み込めません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP112 {
            get {
                return ResourceManager.GetString("EP112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP113：設定されていた{0}が削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP113 {
            get {
                return ResourceManager.GetString("EP113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP114：画像辞書の作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP114 {
            get {
                return ResourceManager.GetString("EP114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP115：出力文字列の長さが最大出力桁数を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP115 {
            get {
                return ResourceManager.GetString("EP115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP116：変換ID重複のため登録できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP116 {
            get {
                return ResourceManager.GetString("EP116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP117：変換ID使用中のため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP117 {
            get {
                return ResourceManager.GetString("EP117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP118：画像辞書ファイルが不正な状態のため、処理を継続できません。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP118 {
            get {
                return ResourceManager.GetString("EP118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP119：{0}は既にマスタ参照または知識処理が設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP119 {
            get {
                return ResourceManager.GetString("EP119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP120：帳票認識ログファイルの削除に失敗しました。管理者に連絡してください。ファイル名は{0}です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP120 {
            get {
                return ResourceManager.GetString("EP120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP121：操作ログファイルの削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP121 {
            get {
                return ResourceManager.GetString("EP121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP122：DBデータ/ログ削除処理にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP122 {
            get {
                return ResourceManager.GetString("EP122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP123：保存済みデータの削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP123 {
            get {
                return ResourceManager.GetString("EP123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP124：直接入力テキストボックス内にOCR項目またはユーザ置換項目以外のチェックリストグループIDが含まれています。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP124 {
            get {
                return ResourceManager.GetString("EP124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP125：同一のグループ項目IDが設定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP125 {
            get {
                return ResourceManager.GetString("EP125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP126：直接入力の参照項目はアクション設定対象のチェックリストグループIDを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP126 {
            get {
                return ResourceManager.GetString("EP126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP127：１つ以上のフレームを作成してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP127 {
            get {
                return ResourceManager.GetString("EP127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP128：「特徴点抽出」を実施してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP128 {
            get {
                return ResourceManager.GetString("EP128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP129：帳票画像ファイルが存在しないため、処理を継続できません。アプリケーションを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP129 {
            get {
                return ResourceManager.GetString("EP129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP130：定義式内に存在しない、または項目種別がOCR項目・ユーザ置換項目のデータ型が文字ではないグループIDが設定されています。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP130 {
            get {
                return ResourceManager.GetString("EP130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP131：定義式内に扱えない演算子または文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP131 {
            get {
                return ResourceManager.GetString("EP131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP132：定義式内に－（減算演算子）が複数含まれています。
        ///日付形式・日付計算の妥当性検査・時間形式の検査・時間計算の妥当性検査　の場合、減算演算子を複数使うことは出来ません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP132 {
            get {
                return ResourceManager.GetString("EP132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP133：定義式内の桁数が不正です。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP133 {
            get {
                return ResourceManager.GetString("EP133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP134：定義式の構文に誤りがあります。演算を行うことができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP134 {
            get {
                return ResourceManager.GetString("EP134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP135：結果式内に存在しない、または項目種別がOCR項目・ユーザ置換項目のデータ型が文字ではないグループIDが設定されています。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP135 {
            get {
                return ResourceManager.GetString("EP135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP136：結果式の構文に誤りがあります。演算を行うことができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP136 {
            get {
                return ResourceManager.GetString("EP136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP137：サービスの起動に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP137 {
            get {
                return ResourceManager.GetString("EP137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP138：サービスの停止に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP138 {
            get {
                return ResourceManager.GetString("EP138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP139：認識処理の開始に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP139 {
            get {
                return ResourceManager.GetString("EP139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP140：出力を行うデータ件数が、最大件数を超えています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP140 {
            get {
                return ResourceManager.GetString("EP140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP141：出力を行うデータ件数が、0件です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP141 {
            get {
                return ResourceManager.GetString("EP141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP142：CSV出力に失敗しました。　←。を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP142 {
            get {
                return ResourceManager.GetString("EP142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP143：サービスが正しくインストールされていません。サービスを開始できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP143 {
            get {
                return ResourceManager.GetString("EP143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP144：サービスの使用期限が切れています。サービスを開始できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP144 {
            get {
                return ResourceManager.GetString("EP144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP145：指定されたの認識ページが帳票画像に存在しません。{0}は帳票識別に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP145 {
            get {
                return ResourceManager.GetString("EP145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP146：帳票画像とマッチするテンプレートが存在しません。{0}は帳票識別に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP146 {
            get {
                return ResourceManager.GetString("EP146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP147：入力値が設定された範囲外です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP147 {
            get {
                return ResourceManager.GetString("EP147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP148：定義式内に入力が不完全な式があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP148 {
            get {
                return ResourceManager.GetString("EP148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP149：参照テーブルまたは項目が存在しません。条件をクリアします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP149 {
            get {
                return ResourceManager.GetString("EP149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP150：指定した知識辞書が存在しません。条件をクリアします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP150 {
            get {
                return ResourceManager.GetString("EP150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP151：利用できない帳票定義が存在します。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP151 {
            get {
                return ResourceManager.GetString("EP151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP152：{0}は帳票識別に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP152 {
            get {
                return ResourceManager.GetString("EP152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP153：ユーザ定義使用中のため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP153 {
            get {
                return ResourceManager.GetString("EP153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP154：最大出力桁数は出力文字列よりも大きな桁数を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP154 {
            get {
                return ResourceManager.GetString("EP154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP155：項目数が最大数に達してしまうため、帳票イメージコピー機能は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP155 {
            get {
                return ResourceManager.GetString("EP155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP156 : 帳票出力先フォルダパスにアクセスできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP156 {
            get {
                return ResourceManager.GetString("EP156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP157 : 利用できる帳票定義が0件のため処理を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP157 {
            get {
                return ResourceManager.GetString("EP157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP158：監視フォルダの入力画像を削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP158 {
            get {
                return ResourceManager.GetString("EP158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP159：ページが未指定の認識ページに別テンプレートの表示グループを含むユーザ定義項目を設定することはできません。
        ///認識ページ：{0}
        ///ユーザ定義ID：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP159 {
            get {
                return ResourceManager.GetString("EP159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP160：通貨記号のいずれかを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP160 {
            get {
                return ResourceManager.GetString("EP160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EP161：ファイル名に使用できない文字「{0}」が使われています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP161 {
            get {
                return ResourceManager.GetString("EP161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果式内に扱えない演算子または文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP162 {
            get {
                return ResourceManager.GetString("EP162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP001：画像辞書を作成しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP001 {
            get {
                return ResourceManager.GetString("IP001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP002：※定義式内には以下の演算子が扱えます。
        ///&amp;（文字列結合演算子） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP002 {
            get {
                return ResourceManager.GetString("IP002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP003：※定義式内には以下の演算子が扱えます。
        ///&amp;（文字列結合演算子）、－（日付減算演算子） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP003 {
            get {
                return ResourceManager.GetString("IP003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP004：※定義式内には以下の演算子が扱えます。
        ///&amp;（文字列結合演算子）、－（時間減算演算子） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP004 {
            get {
                return ResourceManager.GetString("IP004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP005：CSVを出力しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP005 {
            get {
                return ResourceManager.GetString("IP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP006：{0}_{1} の「{2}」確信度は「{3}」です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP006 {
            get {
                return ResourceManager.GetString("IP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP007：{0}_{1}のバーコードを認識します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP007 {
            get {
                return ResourceManager.GetString("IP007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP008：{0}_{1}のバーコード認識結果は「{2}」です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP008 {
            get {
                return ResourceManager.GetString("IP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP009：{0}_{1}のOCR項目を認識します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP009 {
            get {
                return ResourceManager.GetString("IP009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP010：{0}_{1}のOCR項目認識結果は「{2}」です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP010 {
            get {
                return ResourceManager.GetString("IP010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP011：{0}_{1}を「{2}」と識別しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP011 {
            get {
                return ResourceManager.GetString("IP011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP012：帳票取得が不完全なデータが存在します。シーケンスフォルダを削除して処理を再開します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP012 {
            get {
                return ResourceManager.GetString("IP012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP013：シーケンスフォルダ（{0}）を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP013 {
            get {
                return ResourceManager.GetString("IP013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP014：帳票認識が不完全なデータが存在します。帳票画像を削除して処理を再開します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP014 {
            get {
                return ResourceManager.GetString("IP014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP015：項目画像（{0}）を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP015 {
            get {
                return ResourceManager.GetString("IP015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T000：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T000 {
            get {
                return ResourceManager.GetString("T000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T001： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T002： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T003： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T004： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T004 {
            get {
                return ResourceManager.GetString("T004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T005： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T006：DBデータ/ログ削除処理を実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T007：操作ログファイルを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T008：帳票認識ログファイルを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T009：保存済みデータを削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T010：DBデータ/ログ削除処理を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T011：DBデータ/ログ削除処理を完了しました。(異常あり) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
    }
}
