//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRSDKTest {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumNames() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCRSDKTest.EnumNames", typeof(EnumNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    AZTEC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_AZTEC {
            get {
                return ResourceManager.GetString("BarcodeFormat_AZTEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    CODABAR/NW7 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_CODABAR {
            get {
                return ResourceManager.GetString("BarcodeFormat_CODABAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    CODE128 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_CODE_128 {
            get {
                return ResourceManager.GetString("BarcodeFormat_CODE_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///    CODE39 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_CODE_39 {
            get {
                return ResourceManager.GetString("BarcodeFormat_CODE_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///    CODE93 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_CODE_93 {
            get {
                return ResourceManager.GetString("BarcodeFormat_CODE_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///    DATA_MATRIX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_DATA_MATRIX {
            get {
                return ResourceManager.GetString("BarcodeFormat_DATA_MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///    EAN_13 / JAN_13 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_EAN_13 {
            get {
                return ResourceManager.GetString("BarcodeFormat_EAN_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///    EAN_8 / JAN_8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_EAN_8 {
            get {
                return ResourceManager.GetString("BarcodeFormat_EAN_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    ITF　/　Inteleaved2of5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_ITF {
            get {
                return ResourceManager.GetString("BarcodeFormat_ITF", resourceCulture);
            }
        }
        
        /// <summary>
        ///    MAXICODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_MAXICODE {
            get {
                return ResourceManager.GetString("BarcodeFormat_MAXICODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    MSI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_MSI {
            get {
                return ResourceManager.GetString("BarcodeFormat_MSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///    PDF_417 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_PDF_417 {
            get {
                return ResourceManager.GetString("BarcodeFormat_PDF_417", resourceCulture);
            }
        }
        
        /// <summary>
        ///    PLESSEY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_PLESSEY {
            get {
                return ResourceManager.GetString("BarcodeFormat_PLESSEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    QR_CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_QR_CODE {
            get {
                return ResourceManager.GetString("BarcodeFormat_QR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    RSS_14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_RSS_14 {
            get {
                return ResourceManager.GetString("BarcodeFormat_RSS_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///    RSS_EXPANDED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_RSS_EXPANDED {
            get {
                return ResourceManager.GetString("BarcodeFormat_RSS_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    UPC_A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_UPC_A {
            get {
                return ResourceManager.GetString("BarcodeFormat_UPC_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///    UPC_E に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_UPC_E {
            get {
                return ResourceManager.GetString("BarcodeFormat_UPC_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///    UPC_EAN_EXTENSION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarcodeFormat_UPC_EAN_EXTENSION {
            get {
                return ResourceManager.GetString("BarcodeFormat_UPC_EAN_EXTENSION", resourceCulture);
            }
        }
    }
}
